import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { useState } from 'react'
import { useEffect } from 'react'
import {ethers} from "ethers";
import contract_abi from '@src/src/artifacts/contracts/Bank.sol/Bank.json';
const inter = Inter({ subsets: ['latin'] })

const contractAddress = "0x733EF4b50a0c41BA0EA8e37EaFd3166E33aCBcf2";
const BankAbi = contract_abi.abi;

export default function Home() {

  const [isConnected, setIsConnected] = useState(false);
  const [provider, setProvider] = useState();
  const [connectedWallet, setIsConnectedWallet] = useState();
  const [contract, setContract] = useState();
  const [signer, setSigner] = useState();
  const [currentBalance, setCurrentBalance] = useState();

  const connectMetamask = async() => {
    if(typeof window.ethereum !== "undefined") {
      try {
        let wallet = await ethereum.request({ method: "eth_requestAccounts" });
        setIsConnectedWallet(wallet);
        setIsConnected(true);
        const connectedProvider = new ethers.providers.Web3Provider(window.ethereum);
        const s = await connectedProvider.getSigner();
        setProvider(connectedProvider);
        setSigner(s);
      } catch (e) {
        console.log(e);
      }
    }else{
      setIsConnected(false);
    }
  }

  const callContract = async() => {
    const Bank = new ethers.Contract(contractAddress, BankAbi, signer);
    setContract(Bank);
  }

  const balanceInquiry = async() => {
    setCurrentBalance((await contract.bal_inquiry()).toNumber());
  } 

  const deposit = async() => {
    let amount = prompt("DEPOSIT AMOUNT:");
    let dep = await contract.deposit(amount);
    await dep.wait();
    balanceInquiry();
  }

  const withdraw = async() => {
    try {
      let amount = prompt("WITHDRAW AMOUNT:");
      let wit = await contract.withdraw(amount);
      await wit.wait();
      balanceInquiry();
    } catch (e) {
      alert("Unable to withdraw.");
    }
  }

  useEffect(() => {
    if(contract !== undefined) { 
      balanceInquiry();
    }
  }, [contract]);


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {!isConnected && <button onClick={connectMetamask}>CONNECT</button>}
        {isConnected && 
            <div className='flex-div'>
              <button disabled>CONNECTED</button><br/>
              <span><span>WALLET ADDRESS:</span> {connectedWallet}</span>
              {!contract && <button onClick={callContract}>CONNECT SMART CONTRACT</button> }<br/>
              {contract && 
                <div className='flex-div'>
                <button disabled>CONTRACT CONNECTED</button><br/>
                <span><span>BALANCE:</span> {currentBalance}</span><br/>
                <button onClick={deposit}>DEPOSIT</button><br/>
                <button onClick={withdraw}>WITHDRAW</button><br/>
                </div> }
            </div>
        }
      </main>
    </>
  )
}
